### ISSUE TITLE
Remedial award blank verification status is marked as ready

### ISSUE THREAD

**Issue by DEICMSNEW** [Arushdb/cms_devlopment#27]
Some programs remedial award blank verification marked complete and some programs Remedial award blank verification status is marked as ready but pop up gives activity completed.

**Comment by Arushdb** [comment]
Jyoti 
Please look into this issue and discuss with me before putting any solution.
thanks
Arush

**Comment by JyotiMehra7** [comment]
Observation : For ABR activity, after checking verifygraderem query, in case erroList.size > 0 then correctly processed record count is calculated as int cc=studentList.size() - errorList.size(); 
-- here studentList.size() is null and errorList.size > 0, this throws Exceptional Error and catched into logger.info ("Process Can't be started") then finally { code shows the count} but activity is not marked as completed. 
However, in case verifygraderem query returns no error, then ABR activity marked as completed successfully. 

Reason : studentList is null initialized and there is no query mentioned to get studentList.size()

Proposed Solution : total course record that is obtained before grade verification, can be used instead of fetching studentList separately and can be replace in int cc = total - errorList.size()

Code Referred : startActivity method in .../activitymaster/StartActivityDaoImpl.java

**Comment by JyotiMehra7** [comment]
Patch implemented at UAT, but unable to login http://10.154.0.112:8089/CMS/Flex/CMS_FLEX.html  
Error shows "Failed to get roles" even after multiple trials. There is no error at Catalina.out
Kindly suggest

**Comment by JyotiMehra7** [comment]
Grade mismatch error occurred due to data configuration error. Same has been resolved with configuration of appropriate division and respective grade. 
Closing it as there is no code change.
